### ISSUE TITLE
Need to manually call reset method before searching

### ISSUE THREAD

**Issue by benrlodge** [mpneuried/backlunr#1]
Hey @mpneuried - thanks for working on this project - has been very helpful for me. I was wondering though, I needed to manually call the reset method on the collection before calling the search method. I was just wondering if I'm missing something? Do you typically place the reset somewhere before calling your search? I didn't see anything in the documentation about this.

**Comment by mpneuried** [comment]
I found the bug within one of my projects and fixed it
